### ISSUE TITLE
gitbook is deprecated, replace it with mdbook

### ISSUE THREAD

**Issue by makash** [appsecco/attacking-and-auditing-docker-containers-and-kubernetes-clusters#2]
[mdbook](https://github.com/rust-lang/mdBook) is rust based gitbook replacement. gitbook cli is depcreated.

**Comment by abhisek** [comment]
Looks good. Thanks @madhuakula 

Migrated to `mdbook` from `gitbook`

**Comment by madhuakula** [comment]
Now i think you can close this issue 👍
