### ISSUE TITLE
`CTFVMIP` needs to be replaced with `STUDENTVMIP`

### ISSUE THREAD

**Issue by riddhi-shree** [appsecco/attacking-and-auditing-docker-containers-and-kubernetes-clusters#5]
The text in [SSH into the student machine](https://github.com/appsecco/attacking-and-auditing-docker-containers-and-kubernetes-clusters/blob/master/mdbook/src/environment-setup/ssh-into-machine.md#ssh-into-the-student-machine) section incorrectly refers `STUDENTVMIP` as `CTFVMIP`. #4

**Comment by abhisek** [comment]
Fixed by PR #4
