### ISSUE TITLE
Docker Management: Contains typing errors

### ISSUE THREAD

**Issue by riddhi-shree** [appsecco/attacking-and-auditing-docker-containers-and-kubernetes-clusters#7]
1. "Stoping and remove container" should probably be "Stopping and removing container"
2. "Let's run a nginx container" should probably be "Let's run an nginx container"
3. The listed steps do not match the screenshot. 
4. Command to stop the container is listed in the previous step. 
5. "..run the.." is mentioned as "..runt he.."

The above issues have been fixed and a pull request has been raised: #6

**Comment by abhisek** [comment]
Fixed by PR
