### ISSUE TITLE
VBOX_E_FILE_ERROR (0x80BB0004) - Fix

### ISSUE THREAD

**Issue by ls4cfk** [appsecco/attacking-and-auditing-docker-containers-and-kubernetes-clusters#8]
If this error occurs, change the extension from 'ovf' to 'ova'.

**Comment by abhisek** [comment]
Are you recommending us to put this in documentation or are you getting this error?

**Comment by ls4cfk** [comment]
recommending, I had this error and fixed with just changing the extension ( Happened on - 'docker-ctf.ovf')

**Comment by abhisek** [comment]
Thanks. You can raise a PR to fix this issue if you want.

Otherwise, I will fix it later today :)

Thanks
